version: '3.8'

services:
  postgres_erp:
    container_name: postgres-erp
    image: postgres:14.19-alpine3.21
    restart: always
    environment:
      POSTGRES_DB: northwind
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --lc-collate=C --lc-ctype=C"
    volumes:                  
      - postgres_data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - 2001:5432
    networks:
      - plataform-network
volumes:
  postgres_data:

networks:
  plataform-network:
    ipam:
      driver: default
      config:
        - subnet: "172.16.240.0/24"